# Generated by Django 4.2.1 on 2023-06-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(default="", max_length=25),
        ),
    ]
